[workspace]
members = ["cli", "examples/*", "lib", "tests/*"]
resolver = "2"

[workspace.package]
version = "0.0.1-alpha"
edition = "2021"
license = "MIT"

[workspace.dependencies]
bytemuck = { version = "1.25.0", features = ["derive"] }
pinocchio = { git = "https://github.com/anza-xyz/pinocchio/", rev = "009301423f920fd105bd32a25560d127b6f0bf4f" }
