name: Netlify Deployment

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: docs

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Enable pnpm
        run: corepack enable

      - name: Install dependencies (pnpm)
        run: pnpm install

      - name: Build project
        run: pnpm run build

      - name: Install Netlify CLI
        run: npm install -g netlify-cli

      - name: Deploy to Netlify
        id: deploy
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            deployment_info=$(netlify deploy \
            --site=${{ secrets.NETLIFY_PROJECT_ID }} \
            --auth=${{ secrets.NETLIFY_AUTH_TOKEN }}) \
            --json
          else
            deployment_info=$(netlify deploy \
            --prod \
            --site=${{ secrets.NETLIFY_PROJECT_ID }} \
            --auth=${{ secrets.NETLIFY_AUTH_TOKEN }}) \
            --json
          fi

          echo "DEPLOYMENT_INFO=$url" >> $GITHUB_ENV
          echo "DEPLOYMENT_INFO=$url" >> $GITHUB_OUTPUT

      - name: Print deployment info
        run: |
          echo "Deployment info: $DEPLOYMENT_INFO"
